language: node_js
node_js:
  - '6'
script: "npm run build"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: case-study-app-bucket
  endpoint: http://case-study-app-bucket.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  local-dir: build
  skip_cleanup: true
  acl: public_read
